### ISSUE TITLE
Unable to Load Shared Library 'libdl' or one of it's dependencies

### ISSUE THREAD

**Issue by escservices** [chmorgan/sharppcap#288]
SharpPcap Version: 6.0.0.
.NET Version: Core 3.1
OS: Ubuntu 20.04.2 LTS

I have some C# code that uses SharpPcap, it works on Windows but on Linux I'm having trouble getting it to get past the "CaptureDevices.List.Instance part of the code. 

The code compiles without errors or warning but throws this DLL error when running.  Any idea what this could be?  I can't find much online about this error.  

SharpPcap 6.0.0.0, Example4.BasicCapNoCallback.cs

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.dlopen(String filename, Int32 flags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.Resolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()

**Comment by kayoub5** [comment]
what version of libpcap do you have installed? 
what Linux distribution are you using?

**Comment by samuel-pl** [comment]
I'm having the same issue when I make a call to LibPcapLiveDeviceList.Instance. 

`
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.dlopen(String filename, Int32 flags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.Resolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.PcapInterface.GetAllPcapInterfaces()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
`

I am using version 1.5.3 of Libpcap available on 4.14.232-177.418.amzn2.x86_64 (amazon EC2 instance).

Attached is part of LD_DEBUG=all - it seems to freeze before completing.
[ld_debug_output.txt](https://github.com/chmorgan/sharppcap/files/6805741/ld_debug_output.txt)

**Comment by escservices** [comment]
@samuel-pl a few things I found after posting my initial issue.  There seems to be libraries in sharppcap that don't work with dot net 5.0, try 3.1 which is LTS I think.  That fixed some issues.  I fixed another issue by installing libc6-dev on the host OS (sudo apt install libc6-dev) on Ubuntu.  Ultimately, I could never get it to work inside a Snap container without getting the error we both posted about, but the things I mentioned got the app running outside a snap container.

**Comment by samuel-pl** [comment]
@escservices Thanks for the tip. I found that installing glibc-devel.x86_64 seemed to do the trick without needing to downgrade to 5.0. Unfortunately on the amazon instance the call to `LibPcapLiveDeviceList.Instance` returned zero devices, regardless of .NET version. Probably have to keep investigating

**Comment by chmorgan** [comment]
Hello, could you provide some steps to reproduce? @kayoub5 any ideas what might be up?

**Comment by kayoub5** [comment]
libdl used here was not found, it is available in all the CI servers, but seems to be missing in the setup of the reporters of this ticket. 

https://github.com/chmorgan/sharppcap/blob/0801674d28d7ce5995076e2d0c7402e382d12cda/SharpPcap/LibPcap/LibPcapSafeNativeMethods.Resolver.cs#L90-L91

Solution would be to call `NativeLibrary.Load` using reflection.

**Comment by chmorgan** [comment]
@kayoub5 how would that fix the issue again? Is using NativeLibrary.Load replacing the use of libdl calls? Would you be able to make the changes to fix? I'm not sure how many people are being impacted but if its the correct thing to do it might help a number of people with these loading issues.
