### ISSUE TITLE
Can't start project in linux

### ISSUE THREAD

**Issue by ricebus** [chmorgan/sharppcap#37]
Hey

I'm trying to run a project I've built in Ubuntu but SharpPcap can't find libpcap for some reason.
I've installed libpcap & libpcap-dev. I even tried adding a SharpPcap.config.dll like specified in https://github.com/chmorgan/sharppcap/issues/33  but it didn't help.

What am I doing wrong?

`
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'wpcap': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor()
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()
   at PaddingTest.Program.Main(String[] args) in C:\Users\George\Documents\Visual Studio 2017\Projects\PaddingTest\PaddingTest\Program.cs:line 28
Aborted (core dumped)
`

EDIT: Forgot to mention I'm using this under .NET Core

**Comment by ricebus** [comment]
Looks like the lib I was using was published on nuget by someone else, so I'll close this here because it has nothing to do with you :)
