### ISSUE TITLE
Accessviolationexception

### ISSUE THREAD

**Issue by Houzhendong** [chmorgan/sharppcap#53]
I catch a accessviolationexception while calling CaptureDeviceList.Instance ,here are part of exception message 

> at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   at SharpPcap.WinPcap.WinPcapDeviceList.Devices(String rpcapString, RemoteAuthentication remoteAuthentication)
   at SharpPcap.WinPcap.WinPcapDeviceList.Refresh()
   at SharpPcap.WinPcap.WinPcapDeviceList..ctor()
   at SharpPcap.WinPcap.WinPcapDeviceList.get_Instance()
   at SharpPcap.CaptureDeviceList..ctor()
   at SharpPcap.CaptureDeviceList.get_Instance()

how can I solve it?

**Comment by chmorgan** [comment]
It's almost like the required library, npcap, isn't installed. Any more info about your runtime situation? Windows/Linux/Mac? Dotnet, mono?

**Comment by chmorgan** [comment]
Closing as there has been no response.
