### ISSUE TITLE
on win7x64  with npcap-0.991 can not start capture

### ISSUE THREAD

**Issue by cbwang505** [chmorgan/sharppcap#74]
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'SharpPcap.LibPcap.PcapHeader' threw an exception.
  Source=SharpPcap
  StackTrace:
   at SharpPcap.LibPcap.PcapHeader.FromPointer(IntPtr pcap_pkthdr) in E:\git\PeachProject\PeachAdmin\SharpPcap\LibPcap\PcapHeader.cs:line 74
   at SharpPcap.LibPcap.PcapDevice.MarshalRawPacket(IntPtr header, IntPtr data) in E:\git\PeachProject\PeachAdmin\SharpPcap\LibPcap\PcapDevice.cs:line 425
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data) in E:\git\PeachProject\PeachAdmin\SharpPcap\LibPcap\PcapDevice.cs:line 404
   at SharpPcap.LibPcap.Windows.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr) in E:\git\PeachProject\PeachAdmin\SharpPcap\LibPcap\LibPcapSafeNativeMethods.cs:line 231
   at SharpPcap.LibPcap.PcapDevice.CaptureThread() in E:\git\PeachProject\PeachAdmin\SharpPcap\LibPcap\PcapDeviceCaptureLoop.cs:line 355
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

内部异常 1:
FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by chmorgan** [comment]
Are you missing the InteropServices assembly?

https://stackoverflow.com/a/48520796/299037
