### ISSUE TITLE
SEHException: 'External component has thrown an exception.'

### ISSUE THREAD

**Issue by valeriob** [chmorgan/sharppcap#85]
Hi,
i'm trying to run the examples, but i get this exception, do you have any clue to solve it ?
I'm running on windows 10 1903, with winpcap 4.1.3, wireshark works on this machine, i've both tried running as normal user and administrator.

![image](https://user-images.githubusercontent.com/1522516/66632228-413e3480-ec08-11e9-913e-71e2ad14e306.png)

System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

   at SharpPcap.LibPcap.Windows.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_findalldevs(IntPtr& alldevs, StringBuilder errbuf) in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\SharpPcap\LibPcap\LibPcapSafeNativeMethods.cs:line 47
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.GetDevices() in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\SharpPcap\LibPcap\LibPcapLiveDeviceList.cs:line 89
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.Refresh() in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\SharpPcap\LibPcap\LibPcapLiveDeviceList.cs:line 118
   at SharpPcap.LibPcap.LibPcapLiveDeviceList..ctor() in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\SharpPcap\LibPcap\LibPcapLiveDeviceList.cs:line 73
   at SharpPcap.LibPcap.LibPcapLiveDeviceList.get_Instance() in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\SharpPcap\LibPcap\LibPcapLiveDeviceList.cs:line 47
   at Example2.ArpTest.Main(String[] args) in C:\Users\vborioni\Downloads\sharppcap-master\sharppcap-master\Examples\Example2.ArpResolve\Example2.ArpResolve.cs:line 49

Thanks!

**Comment by valeriob** [comment]
My bad, i had both winpcap and npcap installed, but npcap was 0.99-r2, i removed winpcap and updated npcap to 0.9983 and it works 😄
